services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: promptverse_user
      POSTGRES_PASSWORD: promptverse_password
      POSTGRES_DB: promptverse_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
